### ISSUE TITLE
[SERVER]Путь сохранения файла

### ISSUE THREAD

**Issue by anry-das** [group52/TaskManager#13]
При сохранении файла использовать полный путь к файлу (так надежнее)

**Comment by group52** [comment]
ee07e2f

**Comment by anry-das** [comment]
Давайте все же вернемся к старому варианту.
Лучше качественно сделаем #1 , чтобы собирался jar-ник со всеми зависимостями, как нужно.

**Comment by group52** [comment]
911731a
