### ISSUE TITLE
[COMMON]Рефакторинг логгирования

### ISSUE THREAD

**Issue by anry-das** [group52/TaskManager#2]
Необходимо провести рефакторинг логирования:
**log.error(e.getMessage());** это не правильно, нужно сообщение об ишибке (не обязательно) и обязательно стектрейс
**System.out.println(e.getMessage());** вообще не правильно - в приложении должно быть настроено логирование, никаких **System.out.println**
такие конструкции **log.info("get xml model" + s);** должны быть скорее **debug**, чем **info**

**Comment by anry-das** [comment]
Выдержка из лога:
2018-04-04 14:06:15 INFO  XMLParse:569 - findLogin d1
2018-04-04 14:06:15 INFO  XMLParse:497 - addClient d1
2018-04-04 14:06:15 ERROR XMLParse:518 - 
2018-04-04 14:06:15 INFO  XMLParse:642 - changeClient d1
2018-04-04 14:06:15 ERROR XMLParse:660 - 
В XMLParse в строках 518 и 660 что-то происходит, но что - это никому не известно. А все потому, что **log.error(e.getMessage());** и никакого стектрейса.

**Comment by group52** [comment]
e5174d0

**Comment by group52** [comment]
fa96591

**Comment by anry-das** [comment]
В Helper.java все еще есть **e.printStackTrace();**

**Comment by group52** [comment]
fbbcc19
