### ISSUE TITLE
[SERVER]Не корректная структура файла данных

### ISSUE THREAD

**Issue by anry-das** [group52/TaskManager#5]
В файл **controller.xml** сохраняются данные пользователя, но в поле **login** стоит число, как следствие - зайти по логину нельзя.
Также поле **password** не соответствует введенному
Регистрация проходит, но далее при попытке создать задачу получаем ошибку "Unauthorized".
Кроме того, создается впечатления, что в этот файл вообще запись не идет: если его удалить на сервере, то он больше не создается.

**Comment by group52** [comment]
ac95ae9 
Я добавила проверку на наличие файла. Но у меня отображение в самом файле соответствовало действительности и раньше. Если удалять, то файл появляется.

**Comment by anry-das** [comment]
Файл в папке TaskManager\server\xml\?

**Comment by anry-das** [comment]
Вот тут он есть https://github.com/group52/TaskManager/blob/master/server/xml/controller.xml
И данные в нем не очень правильные.
Появлялся он наверное из стрима.
