### ISSUE TITLE
[CLIENT]Добавить сохранение конфигурации

### ISSUE THREAD

**Issue by anry-das** [group52/TaskManager#6]
Необходимо добавить сохранение конфигурации подключения к серверу - IP адрес и порт, чтобы при каждом соединении не указывать вручную.

**Comment by group52** [comment]
Может тогда на welcome form добавить кнопку изменения ip адреса?

**Comment by anry-das** [comment]
Это усложнит логику.
Давайте попроще - файл конфигурации, в котором адрес и порт. При запуске клиента эта информация подтягивается в приложение. Если нужно - изменяем конфиг или один раз ввели в диалоге и все сохранилось.

**Comment by group52** [comment]
поздно я увидел комментарий...

**Comment by group52** [comment]
я сделал без порта(зачем обычному пользователю его вводить?), но зато с кнопкой, сохранил в текстовый файл, который спокойно можно удалять- приложение "не ляжет"

**Comment by group52** [comment]
Release #69

**Comment by anry-das** [comment]
Сейчас если оставить поле ввода пустым и нажать ОК или при недоступности сервера файл конфига перезаписывается пустым значением. Это не правильно.
Сценарий поведения такой:
- перед записью проверить, не пустое ли поле, если пустое, то не записывать
- если сервер недоступен - вывести об этом сообщение и ничего не записывать

Было бы неплохо добавить в конфиг также порт

**Comment by RomanPetrenko** [comment]
1) У меня "если оставить поле ввода пустым и нажать ОК" выбрасывается исключение "field is empty"
2) Файл стирается сразу после нажатия кнопки "изменить ip" (еще перед нажатием "ОК")
Как  я понимаю, мне теперь нужно не затирать файл при нажатии кнопки "изменить ip", а вписывать в него новый адрес при нажатии кнопки "ОК" (с добавлением соотв. исключений сервера и пустого поля), так?

**Comment by anry-das** [comment]
Да. Как правило, сохранение должно происходить после ввода по нажатию ОК, а не тогда, когда пользователь только собирается что-то сделать. А если он передумает и нажмет "Отмена"? А файла уже нет.

**Comment by group52** [comment]
Release #88

**Comment by group52** [comment]
Release #89
